#!/usr/bin/env sh
set -e

# Common constants
COLOR_RESET='\033[0m'
COLOR_GREEN='\033[0;32m'
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-${PWD##*/}}"
TEST_HOST="${TEST_HOST:-localhost}"

echo "Integration test host: ${TEST_HOST}"

get_exposed_port() {
  if [ -z $3 ]
  then
    docker-compose port $1 $2 | cut -d: -f2
  else
    docker-compose port --index=$3 $1 $2 | cut -d: -f2
  fi
}

# Ensure Docker is Running
echo "Docker Information:"
echo ""
docker version
echo ""

mkdir -p build

# Stop any running instances and clean up after them, then pull images
docker-compose down --volumes --remove-orphans
docker-compose up -d --quiet-pull

cat > build/test-environment<<EOF
export DYNAMODB_ENDPOINT=http://${TEST_HOST}:$(get_exposed_port dynalite 8000)
export S3_ENDPOINT=http://${TEST_HOST}:$(get_exposed_port s3 4567)
EOF
